[tool.poetry]
name = "AssetsUpdater"
version = "0.2.2"
description = "Update assets from network."
authors = ["JamzumSum <zzzzss990315@gmail.com>"]
license = "MIT"
homepage = "https://github.com/JamzumSum/AssetsUpdater"
repository = "https://github.com/JamzumSum/AssetsUpdater"

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
packaging = "^21.3"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pytest-asyncio = "^0.18.2"
pre-commit = "^2.17.0"
black = "^22.1.0"
isort = "^5.10.1"

[tool.poetry.extras]
async = [
    "asyncio",
    "aiofiles"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


# customize begin
[tool.pytest.ini_options]
pythonpath = 'src'
asyncio_mode = 'strict'
log_cli = 1
log_cli_level = 'WARNING'

[tool.isort]
profile = "google"

[tool.black]
line-length = 99
target-version = ['py37']
