# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  pull_request_target:
    types:
      - closed
    branches:
      - "release"
      - "release/**"

permissions:
  contents: read

concurrency:
  group: build-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-upload:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'python')
    env:
      GH_TOKEN: ${{ github.token }}
    outputs:
      urls: ${{ steps.upload.outputs.urls }}
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry
      #----------------------------------------------
      #  --------    Build and release   ---------
      #----------------------------------------------
      - name: Build dist
        id: build
        env:
          body: ${{ github.event.pull_request.body }}
        run: |
          version=$(poetry version -s)
          echo "version=$version" >> $GITHUB_ENV

          poetry build

      - name: Upload to Release
        id: upload
        uses: JamzumSum/actions/hash-release@master
        with:
          tag: ${{ env.version }}
          files: dist

  index:
    uses: aioqzone/gh-simple-api/.github/workflows/add.yml@master
    with:
      project: AssetsUpdater
      urls: ${{ needs.build-upload.outputs.urls }}
      repo: aioqzone/aioqzone-index
    # secrets:
    #   REPO_TOKEN: ${{ secrets.PAT }}
