# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  pull_request_target:
    types:
      - closed
    branches:
      - "release"
      - "release/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry
      #----------------------------------------------
      #  --------    Build and release   ---------
      #----------------------------------------------
      - name: Build dist
        id: build
        run: |
          echo "::set-output name=version::$(poetry version -s)"
          poetry build
      - uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: ${{ steps.build.outputs.version }}
          name: ${{ steps.build.outputs.version }}
          generate_release_notes: true
