# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Auto CI

on:
  push:
    branches:
      - dev
      - dev/**
    paths:
      - src/**
      - poetry.lock
      - .github/workflows/ci.yml
      - .github/workflows/test.yml

jobs:
  test:
    uses: ./.github/workflows/test.yml

  merge:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '@no-pr')"
    needs: test
    env:
      TARGET: release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: cliff.toml
          args: -t ${{ needs.test.outputs.package-version }} ${{ env.TARGET }}..HEAD
        env:
          OUTPUT: CHANGELOG.md

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        if: "!contains(github.event.head_commit.message, '@no-pr')"
        with:
          destination_branch: release
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: ${{ needs.test.outputs.package-version }}
          pr_template: CHANGELOG.md
